# Generated by Django 5.0.3 on 2024-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhh', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
